### PR TITLE
Liberty : Network card name

### PR DESCRIPTION
**Pull request by obaviet**
Hello
I install AIO with a comand but my network card name is not eth0
How do i change it?

### CODE REVIEW

**Comment by itlinux** [comment]
edit the /etc/default/grub

add the following to the Centos/ RHEL 
net.ifnames=0 biosdevname=0

make the new grub 

grub2-mkconfig -o /boot/grub2/grub.cfg

Reboot you now have eth0 

Make sure you change the files from the 
/etc/sysconfig/network-scripts/

Remo

**Comment by itlinux** [comment]
I submitted to the github the steps needed. 
Remo

Inviato da iPhone

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack/openstack-ansible!

openstack/openstack-ansible uses Gerrit for code review.

If you have never contributed to OpenStack before make sure you have read the
getting started documentation:
http://docs.openstack.org/infra/manual/developers.html#getting-started

Otherwise please visit
http://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by obaviet** [comment]
Thanks you reply !
i change ok but when i install openstack-ansible  fail

**Comment by obaviet** [comment]
i use ubuntu

**Pull request closed without merging**
